steps:
  - label: "install_ruby"
    commands:
    - "apt update"
  - label: "bundle_install"
    depends_on: "install_ruby"
    command: "bundle install"
  - label: "rake"
    command: "bundle exec rake test"
    depends_on: "bundle_install"
    
