steps:
  - label: "install bundler"
    commands:
        - "apt update"
        - "apt install -y rbenv ruby-build"
        - "rbenv install"
  - label: "test bundle"
    depends_on: "install bundler"
    command: "bundle install"
  - label: "rake"
    command: "bundle exec rake test"
    depends_on: "bundle install"
    
