#!/bin/bash

set -eu

export PATH="$HOME/.rbenv/bin:$PATH"

[ ! -d ~/.rbenv ] && git clone https://github.com/rbenv/rbenv.git ~/.rbenv
[ ! -d ~/.rbenv/plugins/ruby-build ] && git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

eval "$(rbenv init -)"
